### ISSUE TITLE
On most systems shutdown or reboot needs sudo

### ISSUE THREAD

**Issue by sandrodz** [DeadManWalkingTO/ETHminerWatchDogDmW#11]
https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW/blob/master/ETHminerWatchDogDmW.sh#L113

This won't work if script is run by non root user (which is the case in most cases).

On my system I do this by creating a file `/etc/sudoers.d/reboot`
with:
`sandro ALL=NOPASSWD:/sbin/reboot`

Maybe this should be mentioned in Readme?

**Comment by DeadManWalkingTO** [comment]
Yes. Thank you!
