### ISSUE TITLE
Use with amdgpu

### ISSUE THREAD

**Issue by abdullasharapov** [DeadManWalkingTO/ETHminerWatchDogDmW#13]
Can i use WD with amdgpus? When start mining with this script hashrate too low, from 30mh from 1 card to 18mh. What do i wrong?

**Comment by DeadManWalkingTO** [comment]
The script has no effect to mining hash-rate.
Please check the variables and the run command between
```
rem ==================== Your Code Starts Here ====================

rem ==================== Your Code Ends Here ====================
 ```
Normally should be the same with your previous batch file.

ETHminerWatchDogDmW has NO effect to mining hash-rate.
The hash-rate depends on the miner (ethminer).
Thank you!

**Comment by abdullasharapov** [comment]
Thank's for answer. It was my mistake)))) Hash now is ok. One more question. What means command:
#export NO_COLOR=Yes
export CUDA_DEVICE_ORDER=PCI_BUS_ID
It works only with NVIDIA or both with amd?

**Comment by DeadManWalkingTO** [comment]
CUDA only!

**Comment by abdullasharapov** [comment]
that is, your watchdog script can not be used with amd cards?

**Comment by DeadManWalkingTO** [comment]
ETHminerWatchDogDmW works both CUDA and AMD GPUs.

Value `export CUDA_DEVICE_ORDER=PCI_BUS_ID` works only for CUDA devices.

**Comment by DeadManWalkingTO** [comment]
All variables and run commands depends [ethminer](https://github.com/ethereum-mining/ethminer)'s version.
