### ISSUE TITLE
Warning: -S is deprecated. Use the -P parameter instead.

### ISSUE THREAD

**Issue by erkange** [DeadManWalkingTO/ETHminerWatchDogDmW#14]
When i add my codes in the bat file. I am seeing this message in ethminer.
What is right codes to apply?
`
ethminer.exe --report-hashrate --farm-recheck 2000 -U -S eu1.ethermine.org:5555 -FS us1.ethermine.org:5555 -O 0xbc1d0170aa1edd53a7370ebe1c8526b1b056e03a.Rig001 -RH --stratum-ssl
`

**Comment by DeadManWalkingTO** [comment]
just use the new -P syntax.
`ethminer.exe -RH -U --farm-recheck 6000 -P stratum+ssl://0x7013275311fc37ccc1e40193D75086293eCb43A4.testrig@eu1.ethermine.org:5555`
