### ISSUE TITLE
batch wont start

### ISSUE THREAD

**Issue by ghost** [DeadManWalkingTO/ETHminerWatchDogDmW#15]
I've noticed for the past few days that whenever I run the batch file it would hang until I closed and restarted it. The cmd would just stop after saying Etherminer has run 1 times then just stop.

**Comment by DeadManWalkingTO** [comment]
Please give more information.
OS version
Script version
Run command (full run command)
Thank you!

**Comment by ghost** [comment]
Windows 10 Pro version 1803 build 17134,48
Using script 1.9.4 using commands 
"C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile3
ethminer.exe --farm-recheck 200 -P stratum+tcp://ThetaProtocol.PC:x@us-east.ethash-hub.miningpoolhub.com:17020 -U -RH --noeval --cuda-devices 1 -HWMON
Everything else in the batch is untouched.

**Comment by DeadManWalkingTO** [comment]
Now i understand.
1. Use --exit to exit at any error.
2. At stratum use higher --farm-recheck for better performance.
Modify your commands:
```
"C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" -Profile3
ethminer.exe -RH --noeval --farm-recheck 5000 -U --cuda-devices 1 -HWMON -P stratum+tcp://ThetaProtocol.PC:x@us-east.ethash-hub.miningpoolhub.com:17020 
```
That's all.

Additional:
1. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

1. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

Regards,
[DeadManWalking](https://github.com/DeadManWalkingTO)
