### ISSUE TITLE
Error: invalid device ordinal

### ISSUE THREAD

**Issue by king1979** [DeadManWalkingTO/ETHminerWatchDogDmW#16]
Hi, 
i get the above error message when starting the script.

Windows 10 Pro version 1803 build 17134,48
Using script 1.9.4 using commands
ethminer.exe -RH -U --exit -S eu1.ethermine.org:4444 -O (wallet-adress).miner1 -FS us1.ethermine.org:4444 -O (wallet-adress).miner1
Everything else in the batch is untouched.

**Comment by DeadManWalkingTO** [comment]
GPU model?
Driver version?
Ethminer version?

**Comment by king1979** [comment]
- Geforce GTX 1050 ti (Gigabyte GV-N105TOC-4GD)
- Nvidia Driver 397.64
- ethminer 0.14.0

**Comment by pipitonelabs** [comment]
I am also having this issue, 1070's, NVDA driver 398.11, ethminer 0.14.0

**Comment by DeadManWalkingTO** [comment]
Please try the new ETHminerWatchDogDmW version and reply.
Thank you!

**Comment by pipitonelabs** [comment]
Invalid ordinal error gone, but new error - No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument.

This is my main syntax that works for me:

ethminer.exe --cl-global-work 8192 --farm-recheck 200 -U -P stratum1+tcp://walletaddress.worker@us1.ethermine.org:4444

**Comment by DeadManWalkingTO** [comment]
Please try:
```ethminer.exe -v 4 --farm-recheck 6000 -R --display-interval 10 --exit -U -P stratum+ssl://0x7013275311fc37ccc1e40193D75086293eCb43A4.test@eu1.ethermine.org:5555```
or
```ethminer.exe -v 4 --farm-recheck 6000 -R --display-interval 10 --exit -U  -P stratum+tcp://0x7013275311fc37ccc1e40193D75086293eCb43A4.test@eu1.ethermine.org:4444```

and feedback!

Thank you!

**Comment by pipitonelabs** [comment]
Will do

Feature request: disable reboots and allow unlimited miner restarts. This way we can view logs in the morning and tune our GPUs without having downtime overnight. For example - I woke up and my rig rebooted, but I don’t have automatic login enabled.

**Comment by DeadManWalkingTO** [comment]
Reboot fix many mining hardware problems (check ethminer issues).
