### ISSUE TITLE
Compatibility with latest release 0.16.0 dev3

### ISSUE THREAD

**Issue by ianusy2k2** [DeadManWalkingTO/ETHminerWatchDogDmW#17]
i love this  watchdog.... comes really handy.... i was using it on 0.15.0 and working.... tried using it to 0.16 dev3.... same commands and its quite unstable....

**Comment by DeadManWalkingTO** [comment]
I try to find the problem. (Please give me few days. Thank you!)

**Comment by DeadManWalkingTO** [comment]
Fixed.
Thank you!
