### ISSUE TITLE
Make date locale-independent

### ISSUE THREAD

**Issue by XhmikosR** [DeadManWalkingTO/ETHminerWatchDogDmW#3]

**Comment by DeadManWalkingTO** [comment]
It's easy on Win10 with powershell but we need backward compatibility with Win7.
Feel free to find a way ;-)

**Comment by DeadManWalkingTO** [comment]
I think it's ready.
Please check and close the issue.
Thank you!

**Comment by XhmikosR** [comment]
Works fine now.
