### ISSUE TITLE
How can i edit the bat

### ISSUE THREAD

**Issue by ZiDanRO** [DeadManWalkingTO/ETHminerWatchDogDmW#4]
How can i edit so i can run this command.
Because i get invalid argument
`ethminer.exe --farm-recheck 4000 -U -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:14444 -O 0x74B9aad895971b834eE2745917FA8fFxxxxxxxxx.Ziyyyyyyyy --cuda-parallel-hash 4 --cuda-grid-size 4096`

**Comment by DeadManWalkingTO** [comment]
Use any text editor like Notepad or Notepad++ and modify the code between:

```
==================== Your Code Start Here ====================

ethminer.exe --farm-recheck 4000 -U -S eu1.ethermine.org:4444 -FS eu1.ethermine.org:14444 -O 0x74B9aad895971b834eE2745917FA8fFxxxxxxxxx.Ziyyyyyyyy --cuda-parallel-hash 4 --cuda-grid-size 4096

==================== Your Code End Here ====================
```
