### ISSUE TITLE
How to kill the process?

### ISSUE THREAD

**Issue by sandrodz** [DeadManWalkingTO/ETHminerWatchDogDmW#7]
I cannot kill this process on centos7, sending SIGKILL and process comes back up. I understand this is by design, but what if I want to kill it for legitimate reasons, like driver meddling or bios flash.

**Comment by DeadManWalkingTO** [comment]
Don't terminate ethminer process. Watchdog raise the process again.
Need to terminate the watchdog.

**Comment by sandrodz** [comment]
Which one is Watchdog process? I cannot find it :)

**Comment by sandrodz** [comment]
This is it right?
<img width="1207" alt="screen shot 2018-03-10 at 3 52 33 pm" src="https://user-images.githubusercontent.com/8479569/37241973-09064694-247b-11e8-9ad4-a1a42c65ed80.png">

**Comment by DeadManWalkingTO** [comment]
Under normal circumstances, you should only see one ETHminerWatchDogDmW process.
