### ISSUE TITLE
Restart server when hash rate goes to zero

### ISSUE THREAD

**Issue by sandrodz** [DeadManWalkingTO/ETHminerWatchDogDmW#9]
I've issue with one GPU has rate sometimes goes to zero and need restart server to get it back up.

It would be great if your script would monitor this.

**Comment by DeadManWalkingTO** [comment]
Ethminer pool request 757 (added --exit parameter to exit whenever an error occurred).

**Comment by sandrodz** [comment]
It doesn't exit on `GPU hangs in OpenCL call`, as it continues to mine with the other cards.

**Comment by DeadManWalkingTO** [comment]
Try latest Ethminer version. Download (or beter build) the latest.
You can use [ETHminerBuildScriptDmW](https://github.com/DeadManWalkingTO/ETHminerBuildScriptDmW).
Please feedback.
Thank you!
